system_name: heterogeneous_2pis_jetson_final

runtime:
  request_timeout_sec: 30.0

master:
  role: master
  device: cpu

pipeline_order:
  - worker1
  - worker2
  - jetson

workers:
  - worker_id: worker1
    partition_id: 0
    host: 0.0.0.0
    connect_host: 192.168.0.102
    port: 9101
    device: cpu
    next_worker_id: worker2

  - worker_id: worker2
    partition_id: 1
    host: 0.0.0.0
    connect_host: 192.168.0.104
    port: 9102
    device: cpu
    next_worker_id: jetson

  - worker_id: jetson
    partition_id: 2
    host: 0.0.0.0
    connect_host: 192.168.1.110
    port: 9103
    device: gpu
    next_worker_id: null

monitoring:
  network_interface: eth0
