system_name: homogeneous_3workers

runtime:
  request_timeout_sec: 30.0

master:
  role: master
  device: cpu

pipeline_order:
  - worker1
  - worker2
  - worker3

workers:
  - worker_id: worker1
    partition_id: 0
    host: 0.0.0.0
    connect_host: 192.168.1.101
    port: 9101
    device: cpu

  - worker_id: worker2
    partition_id: 1
    host: 0.0.0.0
    connect_host: 192.168.1.102
    port: 9102
    device: cpu

  - worker_id: worker3
    partition_id: 2
    host: 0.0.0.0
    connect_host: 192.168.1.103
    port: 9103
    device: cpu

monitoring:
  network_interface: eth0